Autentication
carrilhorafael/projeto-lab-moveis pull request #3
Opened 2021-11-30 23:03 UTC by BunnyMerz

2021-12-01 00:17 UTC, dbofmmbt requested changes
Parece bacana! Deixei alguns comentários. Além deles, que acha de tentar adicionar alguns testes? Tem libs pra mockar a parte de auth do Firebase:

https://firebase.flutter.dev/docs/testing/testing
https://pub.dev/packages/firebase_auth_mocks

2021-12-01 00:17 UTC, dbofmmbt commented on android/app/build.gradle
> +apply plugin: 'com.google.gms.google-services'
Essas dependências já foram adicionadas anteriormente.

2021-12-01 00:17 UTC, dbofmmbt commented on lib/main.dart
>    @override
No `MyApp` eu usei um `FutureBuilder` para poder inicializar o FlutterFire. A gente realmente precisa desse trecho novo? Me parece redundante ter as duas formas de inicializar o `FirebaseApp`.

2021-12-01 00:17 UTC, dbofmmbt commented on lib/main.dart
>  class MyApp extends StatefulWidget {
Que acha de mover esse código para um arquivo separado?

2021-12-07 22:39 UTC, BunnyMerz commented on android/app/build.gradle
> +apply plugin: 'com.google.gms.google-services'
Onde? Na Main não tem essa dependencia

2021-12-07 22:40 UTC, BunnyMerz commented on lib/main.dart
>  class MyApp extends StatefulWidget {
Não sabia qual arquivo botar, e como estava testando nesse, nesse ficou. Sinta-se livre pra escolher

2021-12-07 22:42 UTC, BunnyMerz commented on lib/main.dart
>    @override
Eu deixei por causa das linhas 84-87 que parecem ser um hook. Mas deve ser redundante sim.

2021-12-08 03:44 UTC, dbofmmbt commented on android/app/build.gradle
> +apply plugin: 'com.google.gms.google-services'
Na branch `develop` já tem. Ela é a referência.

2021-12-11 18:31 UTC, dbofmmbt approved these changes

2021-12-11 18:31 UTC, merged